NAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254

MONEY_MAX_DIGITS = 14
MONEY_DECIMAL_PLACES = 2
AMOUNT_MIN_VALUE = 0.01
MONEY_DEFAULT = 0
OPERATION_TYPE_MAX_LENGTH = 10

WALLET_DETAIL = 'api/v1/wallets/{uuid}'
WALLET_OPERATION = 'api/v1/wallets/{uuid}/operation'
