version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_files:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: slavakulikov/wallet_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_files:/media
  nginx:
    image: slavakulikov/wallet_gateway
    env_file: .env
    ports:
      - 9099:80
    volumes:
      - static_volume:/static
      - media_files:/media
