version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: wallet-db
    image: postgres:17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django_user  -d django" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: wallet-back
    build: ./backend/
    volumes:
      - static:/backend_static
      - media:/media
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        cp -r /app/collected_static/. /backend_static/static/ &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000
      "
    depends_on:
      - db
  nginx:
    container_name: wallet-nginx
    build: ./nginx/
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
