[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
known_first_party = [
    'backend',
    'wallets',
    'core',
    'api',
    'tests',
    'logging_setup'
]
default_section = "THIRDPARTY"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
force_sort_within_sections = true
lines_after_imports = 2
lines_between_types = 1

[tool.black]
line-length = 79