# Generated by Django 4.2.20 on 2025-07-03 21:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Сумма операции",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                help_text="Пользователь, владеющий кошельком",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
